CREATE TABLE ACCOUNTS(
  uuid CHARACTER VARYING(36) NOT NULL PRIMARY KEY,
  creation_time TIMESTAMP NOT NULL,
  modification_time TIMESTAMP NOT NULL,
  length_unit CHARACTER VARYING(255) NOT NULL,
  weight_unit CHARACTER VARYING(255) NOT NULL
);

CREATE TABLE MEASURE_PARAMETERS(
  uuid CHARACTER VARYING(36) NOT NULL PRIMARY KEY,
  creation_time TIMESTAMP NOT NULL,
  modification_time TIMESTAMP NOT NULL,
  account_uuid CHARACTER VARYING(36) NOT NULL REFERENCES ACCOUNTS(uuid) ON DELETE RESTRICT
);
