CREATE TABLE ACCOUNTS(
  uuid CHARACTER VARYING(36) NOT NULL PRIMARY KEY,
  creationtime TIMESTAMP NOT NULL,
  modificationtime TIMESTAMP NOT NULL
);

CREATE TABLE MEASURE_PARAMETERS(
  uuid CHARACTER VARYING(36) NOT NULL PRIMARY KEY,
  creationtime TIMESTAMP NOT NULL,
  modificationtime TIMESTAMP NOT NULL,
  account_uuid CHARACTER VARYING(36) NOT NULL REFERENCES ACCOUNTS(uuid) ON DELETE RESTRICT
);
